#!/bin/sh
# libc370 corpus gate -- DIFFERENTIAL (#48).
#
# Assembles every non-wip libc370 module twice, once with the as370 in the
# working tree and once with an as370 built from a baseline revision, and
# reports which object decks differ.
#
#   check.sh                 compare against origin/main
#   BASE=<rev> check.sh      compare against any revision
#   LIBC370=/path check.sh   libc370 checkout (default ../../libc370)
#
# WHAT IT ANSWERS, and what it does not. This is a REGRESSION guard: "did my
# change move the corpus, and which modules did it move". It is NOT an oracle
# guard -- it cannot tell you as370 was already wrong, because both sides are
# as370. That is #23-full, which wants committed IFOX00 reference decks. The
# suites that DO carry oracles are tests/run.sh (nine reference decks, one of
# them 113 cards of real generated COBOL) and tests/listref.
#
# WHY DIFFERENTIAL RATHER THAN A MANIFEST. Until #48 this compared deck SHA256s
# against a committed manifest, and the manifest decayed until it could no
# longer tell a regression from an intended change -- 74 modules "CHANGED" in
# August, 114 by the end of the month, with nobody having touched as370.
#
# The proposed repair was to pin the libc370 commit the manifest belonged to.
# That cannot work: 710 of the manifest's 737 entries were under src/, and
# `git ls-files 'src/**/*.s'` in libc370 returns ZERO. They are sdk/mklibc.py
# output, which `mklibc.py clean` deletes again, generated by whichever cc370
# happened to be on PATH -- so the baseline depended on three moving inputs, one
# of which exists in no repository at all.
#
# Comparing two as370 binaries over one tree cancels all three: the corpus is
# whatever is on disk, identically on both sides. Nothing decays, nothing needs
# regenerating, and there is no "coverage drift" to detect because both sides
# walk the same list by construction.
cd "$(dirname "$0")/../.." || exit 2                 # -> as370/
ROOT=$(cd .. && pwd)                                 # -> the cc370 checkout
LIBC370=${LIBC370:-../../libc370}
BASE=${BASE:-origin/main}

# Pin the assembly date/time. as370 stamps the END-record IDR with the system
# date and a few modules embed &SYSDATE/&SYSTIME as an eye-catcher (@@crt0,
# @@crt1, @@crtsvc), so two runs a second apart would differ on those alone.
export ASMDATE=01/01/26 ASMTIME=00.00

[ -x ./as370 ] || { echo "corpus: as370 not built (run make first)"; exit 2; }
[ -d "$LIBC370/maclib" ] || { echo "corpus: libc370 not found at $LIBC370 (set LIBC370=)"; exit 2; }
git -C "$ROOT" rev-parse --verify "$BASE" >/dev/null 2>&1 \
    || { echo "corpus: baseline revision '$BASE' not found (set BASE=)"; exit 2; }

TMP=$(mktemp -d) || exit 2
trap 'rm -rf "$TMP"' EXIT INT TERM

# Build the baseline assembler from BASE. The whole as370 subtree is exported,
# not just as370.c, so a revision whose opcode table or headers differ still
# builds. -w rather than -Werror: we want that revision's BEHAVIOUR, and an
# older one need not be warning-clean under today's host compiler.
#
# Compare the SOURCE, not the two binaries: they are built with different flags
# (-w here against -Werror in the Makefile), so identical sources still produce
# different executables. `git diff` against the revision covers uncommitted work
# in the tree as well, which is the case that matters most while developing.
if git -C "$ROOT" diff --quiet "$BASE" -- as370/src as370/include 2>/dev/null; then
    echo "corpus: as370 source is unchanged against $BASE -- nothing to compare"
    exit 0
fi

git -C "$ROOT" archive "$BASE" as370 | tar -x -C "$TMP" || exit 2
cc -O2 -w -I"$TMP/as370/include" -o "$TMP/as370.base" "$TMP/as370/src/as370.c" \
    || { echo "corpus: baseline as370 ($BASE) does not build"; exit 2; }

# every committed .asm/.s under libc370 except the work-in-progress tree
modules() {
    find "$LIBC370" \( -name '*.asm' -o -name '*.s' \) 2>/dev/null |
        grep -v '/wip/' | sed "s|^$LIBC370/||" | sort
}

MAC="-I $LIBC370/maclib -I $LIBC370/sysmac"
moved=0; checked=0; base_only=0; head_only=0
for rel in $(modules); do
    checked=$((checked + 1))
    "$TMP/as370.base" "$LIBC370/$rel" $MAC -o "$TMP/base.obj" >/dev/null 2>&1; brc=$?
    ./as370             "$LIBC370/$rel" $MAC -o "$TMP/head.obj" >/dev/null 2>&1; hrc=$?
    # a module that assembles on one side and not the other is the loudest
    # possible result: report it as its own category rather than as a byte diff.
    #
    # "Assembles" is RC < 8, which is what JCL's COND=(8,LT) meant: severity 4 is
    # a warning, the deck is punched, and the linkage editor ran. as370 had no
    # severity-4 diagnostic at all until #72 (comment cards take part in the
    # column-72 continuation rule), and 21 corpus modules now warn -- every one
    # of them through libc370's vendored sysmac/getmain.macro, whose UTF-8
    # transcription of `||` runs a card past column 72. Their decks are
    # unchanged, which is exactly what this gate is here to say.
    asm_ok() { [ "$1" -lt 8 ]; }
    if ! asm_ok $brc && asm_ok $hrc; then
        echo "corpus: $rel NOW ASSEMBLES (did not under $BASE)"; head_only=$((head_only + 1)); continue
    fi
    if asm_ok $brc && ! asm_ok $hrc; then
        echo "corpus: $rel NO LONGER ASSEMBLES (rc $hrc)"; base_only=$((base_only + 1)); moved=$((moved + 1)); continue
    fi
    asm_ok $brc || continue                           # does not assemble on either side: pre-existing
    cmp -s "$TMP/base.obj" "$TMP/head.obj" || { echo "corpus: $rel MOVED"; moved=$((moved + 1)); }
done

echo "corpus: $checked modules, baseline $BASE"
if [ $moved = 0 ] && [ $head_only = 0 ]; then
    echo "corpus: no module moved -- the working tree's as370 reproduces $BASE deck for deck"
    exit 0
fi
echo "corpus: $moved moved, $head_only newly assembling"
# Non-zero even when the change is intended. A deck that moves is a decision:
# say in the PR which modules moved and why, the way an output-changing change
# has always had to.
exit 1
