*---------------------------------------------------------------
* cc370 issue #52 -- byte-identity oracle for the multi-CSECT shape.
*
* Contributed by the #52 reporter together with IFOX00's own object
* deck for it, kept as tests/ref/hello.obj:
*
* https://gist.github.com/brazilofmux/e7df231d980a3b7d92fae4775d784e4f
*
* This is REAL generated output, not a constructed case: cobc370 (a
* COBOL-74 compiler for MVS 3.8j) emitting a small program that opens
* SYSOUT and writes two lines.  Three CSECTs -- the program, COBWS for
* WORKING-STORAGE, COBRT for the runtime -- with all four ENTRY points
* defined in the THIRD control section and V-type adcons between them.
* That is precisely what #52's owning-section lookup needs, and what
* libc370's corpus cannot supply: 14 multi-CSECT modules there, and not
* one of them has an ENTRY.
*
* Provenance of the reference deck: assembled on an MVS 3.8j guest with
* PGM=IFOX00, SYSGO kept as a catalogued dataset, then extracted host-
* side with dasdseq while MVS was down.  No FTP, no text mode, no card
* reader -- nothing that could have touched a byte.
*
* Needs SYS1.MACLIB's SPIE and TIME, which libc370's sysmac mirror does
* not carry (mvslovers/libc370#155).  tests/run.sh skips this fixture
* when they are absent; SYS1MAC=<dir> points it at an extract.
*---------------------------------------------------------------
*---------------------------------------------------------------
* Generated by cobc370 from hello.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
* DISPLAY and report output are served by our own COBRT runtime.
*---------------------------------------------------------------
HELLO    CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
         USING COBBEG,12
         LA    11,2048(,12)        second code base
         LA    11,2048(,11)
         USING COBBEG+4096,11
         LA    10,2048(,11)        third code base
         LA    10,2048(,10)
         USING COBBEG+8192,10
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
         SPIE  COBSPIE,((1,15))    report program checks by line
T0000    DS    0H
* DISPLAY
         MVC   DSPBUF+0(37),S0001
         LA    1,PARM0001
         L     15,VDISP
         BALR  14,15
T0001    DS    0H
* DISPLAY
         MVC   DSPBUF+0(39),S0002
         LA    1,PARM0002
         L     15,VDISP
         BALR  14,15
T0002    DS    0H
* STOP RUN
         L     15,VTERM            close anything the runtime opened
         BALR  14,15
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
VDISP    DC    V(COBDISP)
VTERM    DC    V(COBTERM)
PARM0001 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0001)  last parameter
LEN0001  DC    H'37'
PARM0002 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0002)  last parameter
LEN0002  DC    H'39'
S0001    DC    CL37'HELLO FROM COBC. NO SYS1.COBLIB HERE.'  nonnumeric
S0002    DC    CL39'SECOND LINE, WITH A QUOTE: DON''T PANIC.'
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
DSPBUF   DS    CL121               DISPLAY line
SAVEAREA DS    18F
* program-check exit: report the source line, then let it abend
COBSPIE  DS    0H
         USING COBSPIE,15
         STM   14,12,SPIEREGS      R15 is our base on entry
         LR    9,15                keep a base across the WTO
         DROP  15
         USING COBSPIE,9
         LR    10,1                the PIE
*  the interruption code, as the digit people know it
         SR    7,7
         IC    7,7(,10)            low byte of the interruption code
         N     7,SPIE15
         LA    7,SPIEHEX(7)
         MVC   SPIECODE(1),0(7)
*  the interrupt address, as an offset into this module
         L     2,8(,10)            second word of the old PSW
         N     2,SPIEADR           leaves the instruction address
         S     2,SPIEBEG           relative to the entry point
*  the last table entry at or before it names the statement
         L     3,SPIETAB
         LH    4,SPIENUM
         SR    5,5                 no line yet
SPIELOOP LTR   4,4
         BZ    SPIEFND
         LH    6,0(,3)             this statement's offset
         CR    6,2
         BH    SPIEFND             past it: the previous one is the ans
         LH    5,2(,3)
         LA    3,4(,3)
         BCTR  4,0
         B     SPIELOOP
SPIEFND  CVD   5,SPIEDW
         UNPK  SPIELINE(5),SPIEDW+5(3)
         OI    SPIELINE+4,X'F0'
         WTO   MF=(E,SPIEWTO)      into the job log, beside the abend
*  cancel the exit and back up to the failing instruction,
*  so the abend happens for real -- same code, same dump
         SR    2,2
         IC    2,7(,10)            the interruption code
         A     2,SPIE3000
         ABEND (2),DUMP
SPIEHEX  DC    C'0123456789ABCDEF'
SPIE15   DC    F'15'
SPIE3000 DC    F'3000'
SPIEADR  DC    X'00FFFFFF'
SPIEBEG  DC    A(COBBEG)
SPIETAB  DC    A(SPIELTB)
SPIENUM  DC    H'3'                statements in the table
SPIEREGS DS    15F
SPIEDW   DS    D
SPIEWTO  WTO   'COBC370: PROGRAM CHECK 0C0 AT SOURCE LINE 00000',      X
               MF=L
SPIECODE EQU   SPIEWTO+29,1        the 0C? digit, patched above
SPIELINE EQU   SPIEWTO+46,5        the line number, likewise
* statement offsets, ascending, paired with source lines
SPIELTB  DS    0H
         DC    AL2(T0000-COBBEG),AL2(6)
         DC    AL2(T0001-COBBEG),AL2(7)
         DC    AL2(T0002-COBBEG),AL2(8)
COBWS    CSECT
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
*---------------------------------------------------------------
* COBRT -- our runtime. Nothing here is from SYS1.COBLIB.
* DISPLAY reaches SYSOUT through QSAM directly, which is the
* same access-method path IKFCBL00 uses for its own file I/O.
* Not reentrant: MVS 3.8j batch does not require it.
*---------------------------------------------------------------
COBRT    CSECT
         ENTRY COBDISP
         ENTRY COBTERM
         ENTRY COBWRL
         ENTRY COBDATE
*
* COBDISP -- write one line to SYSOUT.
*   R1 -> A(text), A(halfword length).  Opens SYSOUT on demand.
*
COBDISP  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE1+4
         LA    11,RTSAVE1
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         CLI   RTOPEN,X'01'        already open?
         BE    COBD010
         OPEN  (RTDCB,OUTPUT)
         MVI   RTOPEN,X'01'
COBD010  MVI   RTLINE,C' '         ASA: single space
         MVC   RTLINE+1(120),RTLINE  blank the text area
         LTR   4,4
         BNP   COBD020             empty: emit a blank line
         CH    4,RTMAX
         BNH   COBD015
         LH    4,RTMAX             truncate at line width
COBD015  BCTR  4,0                 EX wants length-1
         EX    4,COBDMVC
COBD020  PUT   RTDCB,RTLINE
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBDMVC  MVC   RTLINE+1(0),0(2)    executed, never fallen into
*
* COBTERM -- close SYSOUT if COBDISP ever opened it.
*
COBTERM  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE2+4
         LA    11,RTSAVE2
         ST    11,8(13)
         LR    13,11
         CLI   RTOPEN,X'01'
         BNE   COBT010
         CLOSE (RTDCB)
         MVI   RTOPEN,X'00'
COBT010  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
*
* COBDATE -- fill an 8-byte field with MM/DD/YY.
*   R1 -> the field.  TIME DEC hands back the date as packed
*   00YYDDDF, which is Julian, so the day of year has to be
*   walked into a month and a day.
*
COBDATE  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE4+4
         LA    11,RTSAVE4
         ST    11,8(13)
         LR    13,11
         LR    2,1                 the field, before TIME takes R1
         TIME  DEC                 R0 = HHMMSSth, R1 = 00YYDDDF
         ST    1,DTPACK
         UNPK  DTZONE(7),DTPACK(4)  '00YYDDD'
         OI    DTZONE+6,X'F0'
         PACK  DTDW(8),DTZONE+4(3)
         CVB   3,DTDW              day of the year
         PACK  DTDW(8),DTZONE+2(2)
         CVB   4,DTDW              the year
         N     4,DTF3              zero if a leap year -- 1901-2099, so
*                             mod 4 is the whole rule
         LA    5,1                 month
         LA    6,DTMON
DT010    SR    7,7
         IC    7,0(0,6)            days in this month
         CH    5,DTH2              February?
         BNE   DT020
         LTR   4,4
         BNZ   DT020
         LA    7,1(0,7)            29 this year
DT020    CR    3,7
         BNH   DT030               the day falls in this month
         SR    3,7
         LA    5,1(0,5)
         LA    6,1(0,6)
         B     DT010
DT030    CVD   5,DTDW
         UNPK  0(2,2),DTDW+6(2)    MM
         OI    1(2),X'F0'
         MVI   2(2),C'/'
         CVD   3,DTDW
         UNPK  3(2,2),DTDW+6(2)    DD
         OI    4(2),X'F0'
         MVI   5(2),C'/'
         MVC   6(2,2),DTZONE+2     YY, already zoned
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
DTMON    DC    AL1(31,28,31,30,31,30,31,31,30,31,30,31)
DTF3     DC    F'3'
DTH2     DC    H'2'
DTPACK   DS    F
DTZONE   DS    CL8
DTDW     DS    D
RTSAVE4  DS    18F
*
* COBWRL -- advance the paper and write one report line.
*   R1 -> A(dcb), A(current line), A(target line), A(buffer)
*
COBWRL   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE3+4
         LA    11,RTSAVE3
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(dcb)
         L     3,4(0,1)            A(current line)
         L     4,8(0,1)            A(target line)
         L     5,12(0,1)           A(buffer)
         LH    6,0(0,3)
         LH    7,0(0,4)
COBW010  LA    8,1(0,6)
         CR    8,7                 already at the line before the targe
         BNL   COBW020
         PUT   (2),RTBLNK          skip a line
         LA    6,1(0,6)
         B     COBW010
COBW020  PUT   (2),(5)
         STH   7,0(0,3)            current line = target
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
RTBLNK   DC    CL133' '            a blank line, ASA single space
RTSAVE3  DS    18F
RTOPEN   DC    X'00'
RTMAX    DC    H'120'
RTLINE   DC    CL121' '            ASA byte + 120 columns
RTSAVE1  DS    18F
RTSAVE2  DS    18F
RTDCB    DCB   DDNAME=SYSOUT,DSORG=PS,MACRF=(PM),RECFM=FBA,            X
               LRECL=121,BLKSIZE=121
         END

