*---------------------------------------------------------------
* The third full-deck oracle: IFOX00's own object deck for this
* module is tests/ref/ksdsnatr.obj.
*
* Contributed by the #52/#61 reporter, with permission to carry
* it here (#68).  Provenance: tests/ksdsnatr.asm in
* https://github.com/brazilofmux/cobc370 (MIT), generated by
* cobc370 from tests/ksdsnatr.cbl; the IFOX00 side was assembled
* on an MVS 3.8j guest under TK5 with SYSGO kept and pulled off
* the volume host-side.
*
* It is the most informative of the three -- arith carries SRP
* and hello carries the multi-CSECT ENTRY shape, but this one has
* three control sections, VSAM macro expansions and a literal
* pool in a single module, so it regresses three separate rules
* together on real generated code:
*
*   #61  a section's origin rounded up to a doubleword, and its
*        length taken from its own content rather than from the
*        next origin
*   #63  the DCB expansion, which was twelve bytes short here
*        twice over
*   #68  the END literal pool assembled into the FIRST control
*        section -- the twelve bytes that sat in COBRT instead of
*        KSDSNATR, so every literal reference resolved 0x538 away
*
* It went from 1336 differing bytes to byte-identical across
* those three fixes.  This is the module that found each of them,
* and the residual the reporter could not characterise in #61 --
* 28 bytes in the first CSECT, a ST/LA pair twelve apart -- was
* the literal pool.
*
* Needs SYS1.MACLIB's SPIE and TIME (mvslovers/libc370#155); the
* test skips without them.
*---------------------------------------------------------------
*---------------------------------------------------------------
* Generated by cobc370 from ksdsnatr.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
* DISPLAY and report output are served by our own COBRT runtime.
*---------------------------------------------------------------
KSDSNATR CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
         USING COBBEG,12
         LA    11,2048(,12)        second code base
         LA    11,2048(,11)
         USING COBBEG+4096,11
         LA    10,2048(,11)        third code base
         LA    10,2048(,10)
         USING COBBEG+8192,10
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
         SPIE  COBSPIE,((1,15))    report program checks by line
* 000-INITIATE.
P0000    DS    0H
T0000    DS    0H
* DISPLAY
         MVC   DSPBUF+0(34),S0001
         LA    1,PARM0001
         L     15,VDISP
         BALR  14,15
T0001    DS    0H
* DISPLAY
         MVC   DSPBUF+0(34),S0002
         LA    1,PARM0002
         L     15,VDISP
         BALR  14,15
T0002    DS    0H
* DISPLAY
         MVC   DSPBUF+0(1),S0003
         LA    1,PARM0003
         L     15,VDISP
         BALR  14,15
T0003    DS    0H
* OPEN INPUT RECORD-IMAGES
         OPEN  (FD000,INPUT)
T0004    DS    0H
* OPEN I-O KSDS-FILE
         OPEN  (FD001)             VSAM ACB
         LTR   15,15               VSAM request succeeded?
         BZ    G0001
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'30'     permanent error
         B     G0002
G0001    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'00'
G0002    DS    0H
         DROP  8
T0005    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0007(2),S0004      alphanumeric compare
         BE    L0001
T0006    DS    0H
* DISPLAY
         MVC   DSPBUF+0(31),S0005
         MVC   DSPBUF+31(2),D0007
         LA    1,PARM0004
         L     15,VDISP
         BALR  14,15
T0007    DS    0H
* MOVE Y -> END-OF-FILE-SWITCH
         MVC   D0008(1),S0006      literal move, space padded
         DROP  8
L0001    DS    0H
* 010-PROCESS.
P0001    DS    0H
T0008    DS    0H
* PERFORM 110-PROCESS-UPDATES THRU 119-EXIT
L0028    DS    0H
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0008(1),S0006      alphanumeric compare
         BE    L0029
         LA    15,R0001            return here
         ST    15,X0004            into the range's exit cell
         B     P0003
R0001    DS    0H
         DROP  8
         LA    15,F0004            restore fall-through
         ST    15,X0004
         B     L0028
L0029    DS    0H
* 020-TERMINATE.
P0002    DS    0H
T0009    DS    0H
* CLOSE RECORD-IMAGES
         CLOSE (FD000)
T0010    DS    0H
* CLOSE KSDS-FILE
         CLOSE (FD001)
         LTR   15,15               VSAM request succeeded?
         BZ    G0003
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'30'     permanent error
         B     G0004
G0003    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'00'
G0004    DS    0H
         DROP  8
T0011    DS    0H
* STOP RUN
         L     15,VTERM            close anything the runtime opened
         BALR  14,15
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
* 110-PROCESS-UPDATES.
P0003    DS    0H
T0012    DS    0H
* READ RECORD-IMAGES
         LA    1,L0002             this READ's AT END
         STCM  1,7,FD000+33        into DCBEODAD
         L     8,BL0000            base locator
         USING WSC0000,8
         GET   FD000,D0000         QSAM move mode
         B     L0003
L0002    DS    0H                  AT END
         DROP  8
T0013    DS    0H
* MOVE Y -> END-OF-FILE-SWITCH
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0008(1),S0006      literal move, space padded
         DROP  8
L0003    DS    0H
T0014    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0008(1),S0006      alphanumeric compare
         BE    L0004
T0015    DS    0H
* PERFORM 111-DISPATCH THRU 112-EXIT
         LA    15,R0002            return here
         ST    15,X0006            into the range's exit cell
         B     P0005
R0002    DS    0H
         DROP  8
         LA    15,F0006            restore fall-through
         ST    15,X0006
L0004    DS    0H
* 119-EXIT.
P0004    DS    0H
T0016    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0004
         BR    15
F0004    DS    0H                  fall-through when not performed
* 111-DISPATCH.
P0005    DS    0H
T0017    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0001(1),S0007      alphanumeric compare
         BNE   L0005
T0018    DS    0H
* PERFORM 120-ADD-PROCESS THRU 129-EXIT
         LA    15,R0003            return here
         ST    15,X0008            into the range's exit cell
         B     P0007
R0003    DS    0H
         DROP  8
         LA    15,F0008            restore fall-through
         ST    15,X0008
L0005    DS    0H
T0019    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0001(1),S0008      alphanumeric compare
         BNE   L0006
T0020    DS    0H
* PERFORM 130-CHANGE-PROCESS THRU 139-EXIT
         LA    15,R0004            return here
         ST    15,X0010            into the range's exit cell
         B     P0009
R0004    DS    0H
         DROP  8
         LA    15,F0010            restore fall-through
         ST    15,X0010
L0006    DS    0H
T0021    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0001(1),S0009      alphanumeric compare
         BNE   L0007
T0022    DS    0H
* PERFORM 140-DELETE-PROCESS THRU 149-EXIT
         LA    15,R0005            return here
         ST    15,X0014            into the range's exit cell
         B     P0013
R0005    DS    0H
         DROP  8
         LA    15,F0014            restore fall-through
         ST    15,X0014
L0007    DS    0H
* 112-EXIT.
P0006    DS    0H
T0023    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0006
         BR    15
F0006    DS    0H                  fall-through when not performed
* 120-ADD-PROCESS.
P0007    DS    0H
T0024    DS    0H
* MOVE RI-IMAGE -> KSDS-RECORD
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0004(78),D0003     alphanumeric move
         MVI   D0004+78,C' '       space fill the remainder
         MVC   D0004+79(1),D0004+78
T0025    DS    0H
* DISPLAY
         MVC   DSPBUF+0(8),S0010
         MVC   DSPBUF+8(80),D0004
         LA    1,PARM0005
         L     15,VDISP
         BALR  14,15
T0026    DS    0H
* MOVE N -> OP-FAILED-SWITCH
         MVC   D0012(1),S0011      literal move, space padded
T0027    DS    0H
* WRITE KSDS-RECORD
         PUT   RPL=FD001N          VSAM insert by key
         LTR   15,15               stored?
         BNZ   L0008
         LTR   15,15               VSAM request succeeded?
         BZ    G0005
         SHOWCB RPL=FD001N,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'08'        duplicate key
         BE    G0007
         CLI   VSFB+3,X'0C'        key out of sequence
         BE    G0008
         CLI   VSFB+3,X'1C'        cluster is full
         BE    G0009
         MVC   D0007(2),=C'30'     permanent error
         B     G0006
G0007    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'22'     duplicate key
         B     G0006
G0008    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'21'     key out of sequence
         B     G0006
G0009    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'24'     cluster is full
         B     G0006
G0005    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'00'
G0006    DS    0H
         DROP  8
         B     L0009
L0008    DS    0H                  INVALID KEY
         LTR   15,15               VSAM request succeeded?
         BZ    G0010
         SHOWCB RPL=FD001N,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'08'        duplicate key
         BE    G0012
         CLI   VSFB+3,X'0C'        key out of sequence
         BE    G0013
         CLI   VSFB+3,X'1C'        cluster is full
         BE    G0014
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'30'     permanent error
         B     G0011
G0012    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'22'     duplicate key
         B     G0011
G0013    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'21'     key out of sequence
         B     G0011
G0014    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'24'     cluster is full
         B     G0011
G0010    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'00'
G0011    DS    0H
         DROP  8
T0028    DS    0H
* MOVE Y -> OP-FAILED-SWITCH
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0012(1),S0006      literal move, space padded
         DROP  8
L0009    DS    0H
T0029    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0012(1),S0006      alphanumeric compare
         BE    L0010
T0030    DS    0H
* DISPLAY
         MVC   DSPBUF+0(27),S0012
         LA    1,PARM0006
         L     15,VDISP
         BALR  14,15
         DROP  8
L0010    DS    0H
T0031    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0012(1),S0006      alphanumeric compare
         BNE   L0011
         CLC   D0007(2),S0013      alphanumeric compare
         BNE   L0011
T0032    DS    0H
* DISPLAY
         MVC   DSPBUF+0(40),S0014
         LA    1,PARM0007
         L     15,VDISP
         BALR  14,15
         DROP  8
L0011    DS    0H
T0033    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0012(1),S0006      alphanumeric compare
         BNE   L0012
         CLC   D0007(2),S0013      alphanumeric compare
         BE    L0012
T0034    DS    0H
* DISPLAY
         MVC   DSPBUF+0(28),S0015
         MVC   DSPBUF+28(2),D0007
         LA    1,PARM0008
         L     15,VDISP
         BALR  14,15
         DROP  8
L0012    DS    0H
T0035    DS    0H
* DISPLAY
         MVC   DSPBUF+0(1),S0003
         LA    1,PARM0009
         L     15,VDISP
         BALR  14,15
* 129-EXIT.
P0008    DS    0H
T0036    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0008
         BR    15
F0008    DS    0H                  fall-through when not performed
* 130-CHANGE-PROCESS.
P0009    DS    0H
T0037    DS    0H
* PERFORM 150-READ-RECORD THRU 159-EXIT
         LA    15,R0006            return here
         ST    15,X0018            into the range's exit cell
         B     P0017
R0006    DS    0H
         LA    15,F0018            restore fall-through
         ST    15,X0018
T0038    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0010(1),S0006      alphanumeric compare
         BE    L0013
T0039    DS    0H
* DISPLAY
         MVC   DSPBUF+0(30),S0016
         LA    1,PARM0010
         L     15,VDISP
         BALR  14,15
T0040    DS    0H
* DISPLAY
         MVC   DSPBUF+0(1),S0003
         LA    1,PARM0011
         L     15,VDISP
         BALR  14,15
         DROP  8
L0013    DS    0H
T0041    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0010(1),S0006      alphanumeric compare
         BNE   L0014
T0042    DS    0H
* PERFORM 132-DO-CHANGE THRU 133-EXIT
         LA    15,R0007            return here
         ST    15,X0012            into the range's exit cell
         B     P0011
R0007    DS    0H
         DROP  8
         LA    15,F0012            restore fall-through
         ST    15,X0012
L0014    DS    0H
* 139-EXIT.
P0010    DS    0H
T0043    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0010
         BR    15
F0010    DS    0H                  fall-through when not performed
* 132-DO-CHANGE.
P0011    DS    0H
T0044    DS    0H
* DISPLAY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+0(80),D0004
         LA    1,PARM0012
         L     15,VDISP
         BALR  14,15
T0045    DS    0H
* DISPLAY
         MVC   DSPBUF+0(35),S0017
         LA    1,PARM0013
         L     15,VDISP
         BALR  14,15
T0046    DS    0H
* MOVE RI-IMAGE -> KSDS-RECORD
         MVC   D0004(78),D0003     alphanumeric move
         MVI   D0004+78,C' '       space fill the remainder
         MVC   D0004+79(1),D0004+78
T0047    DS    0H
* MOVE N -> OP-FAILED-SWITCH
         MVC   D0012(1),S0011      literal move, space padded
T0048    DS    0H
* REWRITE KSDS-RECORD
         PUT   RPL=FD001R          put the held record back
         LTR   15,15               done?
         BNZ   L0015
         LTR   15,15               VSAM request succeeded?
         BZ    G0015
         SHOWCB RPL=FD001R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'08'        prime key changed
         BE    G0017
         CLI   VSFB+3,X'10'        no such record
         BE    G0018
         CLI   VSFB+3,X'1C'        cluster is full
         BE    G0019
         MVC   D0007(2),=C'30'     permanent error
         B     G0016
G0017    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'21'     prime key changed
         B     G0016
G0018    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'23'     no such record
         B     G0016
G0019    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'24'     cluster is full
         B     G0016
G0015    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'00'
G0016    DS    0H
         DROP  8
         B     L0016
L0015    DS    0H                  INVALID KEY
         LTR   15,15               VSAM request succeeded?
         BZ    G0020
         SHOWCB RPL=FD001R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'08'        prime key changed
         BE    G0022
         CLI   VSFB+3,X'10'        no such record
         BE    G0023
         CLI   VSFB+3,X'1C'        cluster is full
         BE    G0024
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'30'     permanent error
         B     G0021
G0022    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'21'     prime key changed
         B     G0021
G0023    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'23'     no such record
         B     G0021
G0024    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'24'     cluster is full
         B     G0021
G0020    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'00'
G0021    DS    0H
         DROP  8
T0049    DS    0H
* MOVE Y -> OP-FAILED-SWITCH
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0012(1),S0006      literal move, space padded
         DROP  8
L0016    DS    0H
T0050    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0012(1),S0006      alphanumeric compare
         BE    L0017
T0051    DS    0H
* DISPLAY
         MVC   DSPBUF+0(80),D0004
         LA    1,PARM0014
         L     15,VDISP
         BALR  14,15
T0052    DS    0H
* DISPLAY
         MVC   DSPBUF+0(34),S0018
         LA    1,PARM0015
         L     15,VDISP
         BALR  14,15
         DROP  8
L0017    DS    0H
T0053    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0012(1),S0006      alphanumeric compare
         BNE   L0018
T0054    DS    0H
* DISPLAY
         MVC   DSPBUF+0(30),S0019
         MVC   DSPBUF+30(2),D0007
         LA    1,PARM0016
         L     15,VDISP
         BALR  14,15
         DROP  8
L0018    DS    0H
T0055    DS    0H
* DISPLAY
         MVC   DSPBUF+0(1),S0003
         LA    1,PARM0017
         L     15,VDISP
         BALR  14,15
* 133-EXIT.
P0012    DS    0H
T0056    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0012
         BR    15
F0012    DS    0H                  fall-through when not performed
* 140-DELETE-PROCESS.
P0013    DS    0H
T0057    DS    0H
* PERFORM 150-READ-RECORD THRU 159-EXIT
         LA    15,R0008            return here
         ST    15,X0018            into the range's exit cell
         B     P0017
R0008    DS    0H
         LA    15,F0018            restore fall-through
         ST    15,X0018
T0058    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0010(1),S0006      alphanumeric compare
         BE    L0019
T0059    DS    0H
* DISPLAY
         MVC   DSPBUF+0(30),S0016
         LA    1,PARM0018
         L     15,VDISP
         BALR  14,15
T0060    DS    0H
* DISPLAY
         MVC   DSPBUF+0(1),S0003
         LA    1,PARM0019
         L     15,VDISP
         BALR  14,15
         DROP  8
L0019    DS    0H
T0061    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0010(1),S0006      alphanumeric compare
         BNE   L0020
T0062    DS    0H
* PERFORM 142-DO-DELETE THRU 143-EXIT
         LA    15,R0009            return here
         ST    15,X0016            into the range's exit cell
         B     P0015
R0009    DS    0H
         DROP  8
         LA    15,F0016            restore fall-through
         ST    15,X0016
L0020    DS    0H
* 149-EXIT.
P0014    DS    0H
T0063    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0014
         BR    15
F0014    DS    0H                  fall-through when not performed
* 142-DO-DELETE.
P0015    DS    0H
T0064    DS    0H
* DISPLAY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+0(80),D0004
         LA    1,PARM0020
         L     15,VDISP
         BALR  14,15
T0065    DS    0H
* DISPLAY
         MVC   DSPBUF+0(35),S0020
         LA    1,PARM0021
         L     15,VDISP
         BALR  14,15
T0066    DS    0H
* MOVE N -> OP-FAILED-SWITCH
         MVC   D0012(1),S0011      literal move, space padded
T0067    DS    0H
* DELETE KSDS-FILE
         ERASE RPL=FD001R          erase the held record
         LTR   15,15               done?
         BNZ   L0021
         LTR   15,15               VSAM request succeeded?
         BZ    G0025
         SHOWCB RPL=FD001R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'08'        prime key changed
         BE    G0027
         CLI   VSFB+3,X'10'        no such record
         BE    G0028
         CLI   VSFB+3,X'1C'        cluster is full
         BE    G0029
         MVC   D0007(2),=C'30'     permanent error
         B     G0026
G0027    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'21'     prime key changed
         B     G0026
G0028    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'23'     no such record
         B     G0026
G0029    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'24'     cluster is full
         B     G0026
G0025    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'00'
G0026    DS    0H
         DROP  8
         B     L0022
L0021    DS    0H                  INVALID KEY
         LTR   15,15               VSAM request succeeded?
         BZ    G0030
         SHOWCB RPL=FD001R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'08'        prime key changed
         BE    G0032
         CLI   VSFB+3,X'10'        no such record
         BE    G0033
         CLI   VSFB+3,X'1C'        cluster is full
         BE    G0034
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'30'     permanent error
         B     G0031
G0032    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'21'     prime key changed
         B     G0031
G0033    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'23'     no such record
         B     G0031
G0034    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'24'     cluster is full
         B     G0031
G0030    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'00'
G0031    DS    0H
         DROP  8
T0068    DS    0H
* MOVE Y -> OP-FAILED-SWITCH
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0012(1),S0006      literal move, space padded
         DROP  8
L0022    DS    0H
T0069    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0012(1),S0006      alphanumeric compare
         BE    L0023
T0070    DS    0H
* DISPLAY
         MVC   DSPBUF+0(21),S0021
         LA    1,PARM0022
         L     15,VDISP
         BALR  14,15
         DROP  8
L0023    DS    0H
T0071    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0012(1),S0006      alphanumeric compare
         BNE   L0024
T0072    DS    0H
* DISPLAY
         MVC   DSPBUF+0(29),S0022
         MVC   DSPBUF+29(2),D0007
         LA    1,PARM0023
         L     15,VDISP
         BALR  14,15
         DROP  8
L0024    DS    0H
T0073    DS    0H
* DISPLAY
         MVC   DSPBUF+0(1),S0003
         LA    1,PARM0024
         L     15,VDISP
         BALR  14,15
* 143-EXIT.
P0016    DS    0H
T0074    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0016
         BR    15
F0016    DS    0H                  fall-through when not performed
* 150-READ-RECORD.
P0017    DS    0H
T0075    DS    0H
* MOVE RI-IMAGE -> KSDS-RECORD
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0004(78),D0003     alphanumeric move
         MVI   D0004+78,C' '       space fill the remainder
         MVC   D0004+79(1),D0004+78
T0076    DS    0H
* DISPLAY
         MVC   DSPBUF+0(20),S0023
         MVC   DSPBUF+20(10),D0005
         LA    1,PARM0025
         L     15,VDISP
         BALR  14,15
T0077    DS    0H
* MOVE Y -> FOUND-SWITCH
         MVC   D0010(1),S0006      literal move, space padded
T0078    DS    0H
* READ KSDS-FILE
         GET   RPL=FD001R          VSAM retrieval by key
         LTR   15,15               got a record?
         BNZ   L0025
         LTR   15,15               VSAM request succeeded?
         BZ    G0035
         SHOWCB RPL=FD001R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'10'        no such record
         BE    G0037
         MVC   D0007(2),=C'30'     permanent error
         B     G0036
G0037    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'23'     no such record
         B     G0036
G0035    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'00'
G0036    DS    0H
         DROP  8
         B     L0026
L0025    DS    0H                  INVALID KEY
         LTR   15,15               VSAM request succeeded?
         BZ    G0038
         SHOWCB RPL=FD001R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'10'        no such record
         BE    G0040
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'30'     permanent error
         B     G0039
G0040    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'23'     no such record
         B     G0039
G0038    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(2),=C'00'
G0039    DS    0H
         DROP  8
T0079    DS    0H
* MOVE N -> FOUND-SWITCH
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0010(1),S0011      literal move, space padded
         DROP  8
L0026    DS    0H
T0080    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0010(1),S0006      alphanumeric compare
         BE    L0027
         CLC   D0007(2),S0024      alphanumeric compare
         BE    L0027
T0081    DS    0H
* DISPLAY
         MVC   DSPBUF+0(27),S0025
         MVC   DSPBUF+27(2),D0007
         LA    1,PARM0026
         L     15,VDISP
         BALR  14,15
         DROP  8
L0027    DS    0H
* 159-EXIT.
P0018    DS    0H
T0082    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0018
         BR    15
F0018    DS    0H                  fall-through when not performed
X0004    DC    A(F0004)            119-EXIT
X0006    DC    A(F0006)            112-EXIT
X0008    DC    A(F0008)            129-EXIT
X0010    DC    A(F0010)            139-EXIT
X0012    DC    A(F0012)            133-EXIT
X0014    DC    A(F0014)            149-EXIT
X0016    DC    A(F0016)            143-EXIT
X0018    DC    A(F0018)            159-EXIT
VDISP    DC    V(COBDISP)
VTERM    DC    V(COBTERM)
PARM0001 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0001)  last parameter
LEN0001  DC    H'34'
PARM0002 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0002)  last parameter
LEN0002  DC    H'34'
PARM0003 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0003)  last parameter
LEN0003  DC    H'1'
PARM0004 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0004)  last parameter
LEN0004  DC    H'33'
PARM0005 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0005)  last parameter
LEN0005  DC    H'88'
PARM0006 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0006)  last parameter
LEN0006  DC    H'27'
PARM0007 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0007)  last parameter
LEN0007  DC    H'40'
PARM0008 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0008)  last parameter
LEN0008  DC    H'30'
PARM0009 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0009)  last parameter
LEN0009  DC    H'1'
PARM0010 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0010)  last parameter
LEN0010  DC    H'30'
PARM0011 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0011)  last parameter
LEN0011  DC    H'1'
PARM0012 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0012)  last parameter
LEN0012  DC    H'80'
PARM0013 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0013)  last parameter
LEN0013  DC    H'35'
PARM0014 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0014)  last parameter
LEN0014  DC    H'80'
PARM0015 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0015)  last parameter
LEN0015  DC    H'34'
PARM0016 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0016)  last parameter
LEN0016  DC    H'32'
PARM0017 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0017)  last parameter
LEN0017  DC    H'1'
PARM0018 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0018)  last parameter
LEN0018  DC    H'30'
PARM0019 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0019)  last parameter
LEN0019  DC    H'1'
PARM0020 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0020)  last parameter
LEN0020  DC    H'80'
PARM0021 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0021)  last parameter
LEN0021  DC    H'35'
PARM0022 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0022)  last parameter
LEN0022  DC    H'21'
PARM0023 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0023)  last parameter
LEN0023  DC    H'31'
PARM0024 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0024)  last parameter
LEN0024  DC    H'1'
PARM0025 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0025)  last parameter
LEN0025  DC    H'30'
PARM0026 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0026)  last parameter
LEN0026  DC    H'29'
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL8
PWK2     DS    PL8
EDSRC    DS    PL8                 ED source, exactly sized
EDWK     DS    CL64                ED pattern and result
MULT8    DS    PL8                 MP right operand
DIVR8    DS    PL8                 DP divisor
QTMP     DS    PL8                 DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
* file control blocks
FD000    DCB   DDNAME=CARDIN,DSORG=PS,MACRF=(GM)
FD001    ACB   DDNAME=KSDSF01,MACRF=(KEY,DIR,OUT)  VSAM access method c
FD001R   RPL   ACB=FD001,AREA=D0004,                                   X
               AREALEN=80,RECLEN=80,ARG=D0005,KEYLEN=10,OPTCD=(KEY,DIR,X
               KEQ,UPD,MVE)
FD001N   RPL   ACB=FD001,AREA=D0004,                                   X
               AREALEN=80,RECLEN=80,ARG=D0005,KEYLEN=10,OPTCD=(KEY,DIR,X
               KEQ,NUP,MVE)
S0001    DC    CL34'KSDSRAND: READ/REWRITE KSDS DIRECT'  nonnumeric con
S0002    DC    CL34'----------------------------------'
S0003    DC    CL1' '
S0004    DC    CL2'00'
S0005    DC    CL31'VSAM ERROR DURING OPEN, STATUS '
S0006    DC    CL1'Y'
S0007    DC    CL1'A'
S0008    DC    CL1'C'
S0009    DC    CL1'D'
S0010    DC    CL8'ADDING: '
S0011    DC    CL1'N'
S0012    DC    CL27'               RECORD ADDED'
S0013    DC    CL2'22'
S0014    DC    CL40'            *** DUPLICATE RECORD ON FILE'
S0015    DC    CL28'VSAM ERROR ON WRITE, STATUS '
S0016    DC    CL30'          *** RECORD NOT FOUND'
S0017    DC    CL35'               RECORD BEFORE CHANGE'
S0018    DC    CL34'               RECORD AFTER CHANGE'
S0019    DC    CL30'VSAM ERROR ON REWRITE, STATUS '
S0020    DC    CL35'               RECORD BEFORE DELETE'
S0021    DC    CL21'             DELETED '
S0022    DC    CL29'VSAM ERROR ON DELETE, STATUS '
S0023    DC    CL20'ATTEMPTING TO READ: '
S0024    DC    CL2'23'
S0025    DC    CL27'VSAM ERROR ON READ, STATUS '
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
DSPBUF   DS    CL121               DISPLAY line
VSFB     DS    F                   VSAM SHOWCB feedback word
SAVEAREA DS    18F
* program-check exit: report the source line, then let it abend
COBSPIE  DS    0H
         USING COBSPIE,15
         STM   14,12,SPIEREGS      R15 is our base on entry
         LR    9,15                keep a base across the WTO
         DROP  15
         USING COBSPIE,9
         LR    10,1                the PIE
*  the interruption code, as the digit people know it
         SR    7,7
         IC    7,7(,10)            low byte of the interruption code
         N     7,SPIE15
         LA    7,SPIEHEX(7)
         MVC   SPIECODE(1),0(7)
*  the interrupt address, as an offset into this module
         L     2,8(,10)            second word of the old PSW
         N     2,SPIEADR           leaves the instruction address
         S     2,SPIEBEG           relative to the entry point
*  the last table entry at or before it names the statement
         L     3,SPIETAB
         LH    4,SPIENUM
         SR    5,5                 no line yet
SPIELOOP LTR   4,4
         BZ    SPIEFND
         LH    6,0(,3)             this statement's offset
         CR    6,2
         BH    SPIEFND             past it: the previous one is the ans
         LH    5,2(,3)
         LA    3,4(,3)
         BCTR  4,0
         B     SPIELOOP
SPIEFND  CVD   5,SPIEDW
         UNPK  SPIELINE(5),SPIEDW+5(3)
         OI    SPIELINE+4,X'F0'
         WTO   MF=(E,SPIEWTO)      into the job log, beside the abend
*  cancel the exit and back up to the failing instruction,
*  so the abend happens for real -- same code, same dump
         SR    2,2
         IC    2,7(,10)            the interruption code
         A     2,SPIE3000
         ABEND (2),DUMP
SPIEHEX  DC    C'0123456789ABCDEF'
SPIE15   DC    F'15'
SPIE3000 DC    F'3000'
SPIEADR  DC    X'00FFFFFF'
SPIEBEG  DC    A(COBBEG)
SPIETAB  DC    A(SPIELTB)
SPIENUM  DC    H'83'               statements in the table
SPIEREGS DS    15F
SPIEDW   DS    D
SPIEWTO  WTO   'COBC370: PROGRAM CHECK 0C0 AT SOURCE LINE 00000',      X
               MF=L
SPIECODE EQU   SPIEWTO+29,1        the 0C? digit, patched above
SPIELINE EQU   SPIEWTO+46,5        the line number, likewise
* statement offsets, ascending, paired with source lines
SPIELTB  DS    0H
         DC    AL2(T0000-COBBEG),AL2(38)
         DC    AL2(T0001-COBBEG),AL2(39)
         DC    AL2(T0002-COBBEG),AL2(40)
         DC    AL2(T0003-COBBEG),AL2(41)
         DC    AL2(T0004-COBBEG),AL2(42)
         DC    AL2(T0005-COBBEG),AL2(44)
         DC    AL2(T0006-COBBEG),AL2(44)
         DC    AL2(T0007-COBBEG),AL2(45)
         DC    AL2(T0008-COBBEG),AL2(47)
         DC    AL2(T0009-COBBEG),AL2(49)
         DC    AL2(T0010-COBBEG),AL2(50)
         DC    AL2(T0011-COBBEG),AL2(51)
         DC    AL2(T0012-COBBEG),AL2(54)
         DC    AL2(T0013-COBBEG),AL2(54)
         DC    AL2(T0014-COBBEG),AL2(56)
         DC    AL2(T0015-COBBEG),AL2(56)
         DC    AL2(T0016-COBBEG),AL2(58)
         DC    AL2(T0017-COBBEG),AL2(61)
         DC    AL2(T0018-COBBEG),AL2(61)
         DC    AL2(T0019-COBBEG),AL2(63)
         DC    AL2(T0020-COBBEG),AL2(63)
         DC    AL2(T0021-COBBEG),AL2(65)
         DC    AL2(T0022-COBBEG),AL2(65)
         DC    AL2(T0023-COBBEG),AL2(67)
         DC    AL2(T0024-COBBEG),AL2(69)
         DC    AL2(T0025-COBBEG),AL2(70)
         DC    AL2(T0026-COBBEG),AL2(71)
         DC    AL2(T0027-COBBEG),AL2(73)
         DC    AL2(T0028-COBBEG),AL2(73)
         DC    AL2(T0029-COBBEG),AL2(75)
         DC    AL2(T0030-COBBEG),AL2(75)
         DC    AL2(T0031-COBBEG),AL2(77)
         DC    AL2(T0032-COBBEG),AL2(77)
         DC    AL2(T0033-COBBEG),AL2(79)
         DC    AL2(T0034-COBBEG),AL2(79)
         DC    AL2(T0035-COBBEG),AL2(80)
         DC    AL2(T0036-COBBEG),AL2(82)
         DC    AL2(T0037-COBBEG),AL2(84)
         DC    AL2(T0038-COBBEG),AL2(86)
         DC    AL2(T0039-COBBEG),AL2(86)
         DC    AL2(T0040-COBBEG),AL2(87)
         DC    AL2(T0041-COBBEG),AL2(89)
         DC    AL2(T0042-COBBEG),AL2(89)
         DC    AL2(T0043-COBBEG),AL2(91)
         DC    AL2(T0044-COBBEG),AL2(93)
         DC    AL2(T0045-COBBEG),AL2(94)
         DC    AL2(T0046-COBBEG),AL2(95)
         DC    AL2(T0047-COBBEG),AL2(96)
         DC    AL2(T0048-COBBEG),AL2(98)
         DC    AL2(T0049-COBBEG),AL2(98)
         DC    AL2(T0050-COBBEG),AL2(100)
         DC    AL2(T0051-COBBEG),AL2(100)
         DC    AL2(T0052-COBBEG),AL2(101)
         DC    AL2(T0053-COBBEG),AL2(103)
         DC    AL2(T0054-COBBEG),AL2(103)
         DC    AL2(T0055-COBBEG),AL2(104)
         DC    AL2(T0056-COBBEG),AL2(106)
         DC    AL2(T0057-COBBEG),AL2(108)
         DC    AL2(T0058-COBBEG),AL2(110)
         DC    AL2(T0059-COBBEG),AL2(110)
         DC    AL2(T0060-COBBEG),AL2(111)
         DC    AL2(T0061-COBBEG),AL2(113)
         DC    AL2(T0062-COBBEG),AL2(113)
         DC    AL2(T0063-COBBEG),AL2(115)
         DC    AL2(T0064-COBBEG),AL2(117)
         DC    AL2(T0065-COBBEG),AL2(118)
         DC    AL2(T0066-COBBEG),AL2(119)
         DC    AL2(T0067-COBBEG),AL2(121)
         DC    AL2(T0068-COBBEG),AL2(121)
         DC    AL2(T0069-COBBEG),AL2(123)
         DC    AL2(T0070-COBBEG),AL2(123)
         DC    AL2(T0071-COBBEG),AL2(125)
         DC    AL2(T0072-COBBEG),AL2(125)
         DC    AL2(T0073-COBBEG),AL2(126)
         DC    AL2(T0074-COBBEG),AL2(128)
         DC    AL2(T0075-COBBEG),AL2(130)
         DC    AL2(T0076-COBBEG),AL2(131)
         DC    AL2(T0077-COBBEG),AL2(132)
         DC    AL2(T0078-COBBEG),AL2(134)
         DC    AL2(T0079-COBBEG),AL2(134)
         DC    AL2(T0080-COBBEG),AL2(136)
         DC    AL2(T0081-COBBEG),AL2(136)
         DC    AL2(T0082-COBBEG),AL2(138)
COBWS    CSECT
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
D0000    DS    0CL80               RECORD-IMAGE (01 group)
D0001    DC    CL1' '              RI-ACTION PIC X(1)
D0002    DC    CL1' '              FILL0002 PIC X(1)
D0003    DC    CL78' '             RI-IMAGE PIC X(78)
D0004    DS    0CL80               KSDS-RECORD (01 group)
D0005    DC    CL10' '             KR-KEY PIC X(10)
D0006    DC    CL70' '             FILL0006 PIC X(70)
D0007    DC    CL2'00'             WS-STATUS PIC X(2)
         DS    XL6                 reserve the rest of a table
D0008    DC    CL1'N'              END-OF-FILE-SWITCH PIC X(1)
         DS    XL7                 reserve the rest of a table
D0010    DC    CL1'Y'              FOUND-SWITCH PIC X(1)
         DS    XL7                 reserve the rest of a table
D0012    DC    CL1'N'              OP-FAILED-SWITCH PIC X(1)
*---------------------------------------------------------------
* COBRT -- our runtime. Nothing here is from SYS1.COBLIB.
* DISPLAY reaches SYSOUT through QSAM directly, which is the
* same access-method path IKFCBL00 uses for its own file I/O.
* Not reentrant: MVS 3.8j batch does not require it.
*---------------------------------------------------------------
COBRT    CSECT
         ENTRY COBDISP,COBTERM,COBWRL,COBDATE
*
* COBDISP -- write one line to SYSOUT.
*   R1 -> A(text), A(halfword length).  Opens SYSOUT on demand.
*
COBDISP  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE1+4
         LA    11,RTSAVE1
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         CLI   RTOPEN,X'01'        already open?
         BE    COBD010
         OPEN  (RTDCB,OUTPUT)
         MVI   RTOPEN,X'01'
COBD010  MVI   RTLINE,C' '         ASA: single space
         MVC   RTLINE+1(120),RTLINE  blank the text area
         LTR   4,4
         BNP   COBD020             empty: emit a blank line
         CH    4,RTMAX
         BNH   COBD015
         LH    4,RTMAX             truncate at line width
COBD015  BCTR  4,0                 EX wants length-1
         EX    4,COBDMVC
COBD020  PUT   RTDCB,RTLINE
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBDMVC  MVC   RTLINE+1(0),0(2)    executed, never fallen into
*
* COBTERM -- close SYSOUT if COBDISP ever opened it.
*
COBTERM  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE2+4
         LA    11,RTSAVE2
         ST    11,8(13)
         LR    13,11
         CLI   RTOPEN,X'01'
         BNE   COBT010
         CLOSE (RTDCB)
         MVI   RTOPEN,X'00'
COBT010  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
*
* COBDATE -- fill an 8-byte field with MM/DD/YY.
*   R1 -> the field.  TIME DEC hands back the date as packed
*   00YYDDDF, which is Julian, so the day of year has to be
*   walked into a month and a day.
*
COBDATE  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE4+4
         LA    11,RTSAVE4
         ST    11,8(13)
         LR    13,11
         LR    2,1                 the field, before TIME takes R1
         TIME  DEC                 R0 = HHMMSSth, R1 = 00YYDDDF
         ST    1,DTPACK
         UNPK  DTZONE(7),DTPACK(4)  '00YYDDD'
         OI    DTZONE+6,X'F0'
         PACK  DTDW(8),DTZONE+4(3)
         CVB   3,DTDW              day of the year
         PACK  DTDW(8),DTZONE+2(2)
         CVB   4,DTDW              the year
         N     4,DTF3              zero if a leap year -- 1901-2099, so
*                             mod 4 is the whole rule
         LA    5,1                 month
         LA    6,DTMON
DT010    SR    7,7
         IC    7,0(0,6)            days in this month
         CH    5,DTH2              February?
         BNE   DT020
         LTR   4,4
         BNZ   DT020
         LA    7,1(0,7)            29 this year
DT020    CR    3,7
         BNH   DT030               the day falls in this month
         SR    3,7
         LA    5,1(0,5)
         LA    6,1(0,6)
         B     DT010
DT030    CVD   5,DTDW
         UNPK  0(2,2),DTDW+6(2)    MM
         OI    1(2),X'F0'
         MVI   2(2),C'/'
         CVD   3,DTDW
         UNPK  3(2,2),DTDW+6(2)    DD
         OI    4(2),X'F0'
         MVI   5(2),C'/'
         MVC   6(2,2),DTZONE+2     YY, already zoned
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
DTMON    DC    AL1(31,28,31,30,31,30,31,31,30,31,30,31)
DTF3     DC    F'3'
DTH2     DC    H'2'
DTPACK   DS    F
DTZONE   DS    CL8
DTDW     DS    D
RTSAVE4  DS    18F
*
* COBWRL -- advance the paper and write one report line.
*   R1 -> A(dcb), A(current line), A(target line), A(buffer)
*
COBWRL   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE3+4
         LA    11,RTSAVE3
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(dcb)
         L     3,4(0,1)            A(current line)
         L     4,8(0,1)            A(target line)
         L     5,12(0,1)           A(buffer)
         LH    6,0(0,3)
         LH    7,0(0,4)
COBW010  LA    8,1(0,6)
         CR    8,7                 already at the line before the targe
         BNL   COBW020
         PUT   (2),RTBLNK          skip a line
         LA    6,1(0,6)
         B     COBW010
COBW020  PUT   (2),(5)
         STH   7,0(0,3)            current line = target
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
RTBLNK   DC    CL133' '            a blank line, ASA single space
RTSAVE3  DS    18F
RTOPEN   DC    X'00'
RTMAX    DC    H'120'
RTLINE   DC    CL121' '            ASA byte + 120 columns
RTSAVE1  DS    18F
RTSAVE2  DS    18F
RTDCB    DCB   DDNAME=SYSOUT,DSORG=PS,MACRF=(PM),RECFM=FBA,            X
               LRECL=121,BLKSIZE=121
         END
