#import "../bookmaster/bookmaster.typ": *

= Writing Assembler Code <ug-asm>

#idx("assembler language", "writing")
Most programs for MVS 3.8j built with cc370 are written in C, but some
things are easier, or only possible, in assembler language: a short routine
that uses an instruction the compiler does not generate, a system service
that has no C interface, or an existing assembler module that you want to
keep. This chapter shows how to assemble such code with as370, where the
macros it needs come from, and how assembler code and C code call each
other.

The example of this chapter, and of the chapters that follow, is a program
called SUMUP. It adds the numbers it is given as its parameter and prints
the sum and the average. The work is divided between C and assembler:

- #cmd("sumup.c"), the main program in C, converts the parameter into
  numbers\;
- #cmd("addup.asm"), an assembler routine that C calls, adds them\;
- #cmd("report.asm"), an assembler routine that calls the C library
  function #cmd("printf"), prints the result.

The chapter begins with GREET, a program written entirely in assembler.
@ug-link puts both programs into one load library, @ug-transfer sends it to
MVS, @ug-run runs it, and @ug-diag finds the error that SUMUP still
contains.

Every option of as370 is described in the _CC/370 Command Reference_,
Chapter 2, “The as370 Command”.

== Assembling a Program <ug-asm-assemble>

#idx("as370", "assembling a program")
@ug-asm-greet shows GREET, a program that writes a message to the operator
console and ends with return code 0. It uses three macros of the MVS macro
library: #cmd("SAVE"), #cmd("WTO") and #cmd("RETURN").

#fig(caption: [GREET, a program in assembler language])[
  #code(read("../ex/ug-asm/greet.asm"), numbers: true)
] <ug-asm-greet>

The source is an ordinary file on your workstation, with the statements in
the columns that the MVS assembler expects: the name in column 1, the
operation after it, and nothing beyond column 71. A character in column 72
marks a continuation, as it does on MVS. Write the source in plain ASCII, or
in UTF-8 or Latin-1 where you need a character such as #cmd("¬")\; as370
translates it to EBCDIC.

To build GREET:

+ Assemble the source into an object module:
  ```
  as370 -o greet.o greet.asm
  ```
  as370 writes nothing when the assembly is clean. *Give #cmd("-o")*:
  without it, as370 writes no object module.
+ Link the object module into a load module, and write the TRANSMIT file
  that carries it to MVS:
  ```
  ld370 -o GREET greet.o -xmit
  ```
  The member is called #cmd("GREET"), after the #cmd("-o") file. The entry
  point is the one named on the #cmd("END") statement.
+ Check the result with file370, if you like.

@ug-asm-greet-session shows the three steps.

#fig(caption: [Assembling and linking GREET])[
  #screen(raw(read("../ex/ug-asm/greet.txt")))
] <ug-asm-greet-session>

#idx("as370", "return codes")
as370 ends with the return code of the MVS assembler: 0 when the assembly is
clean, 4 for warnings, 8 for errors, 12 for severe errors and 16 when it
could not complete. Each statement in error is shown on standard error with
its line number, as in @ug-asm-clock-session below. An object module with an
error of severity 8 is written, but it is not expected to run: correct the
source before you link it.

#note[When cc370 runs as370, a warning (4) is shown and the build goes on
with the object module\; return code 8 or higher fails the build, and the
object module is not kept.]

#idx("listing", "assembler")
To obtain an assembler listing, add #cmd("-a=")#var("file"). The listing has
the layout of the IFOX00 listing, with the external symbol dictionary, the
source and generated statements, the relocation dictionary and the
cross-reference. @ug-diag shows how to use it.

GREET is linked without the C library. It needs none: it calls no C function
and does not use the C start-up. The C library is linked only when a program
needs it, as the following sections show.

== Macro Libraries <ug-asm-maclib>

#idx("macro library")
#idx("SYS1.MACLIB")
On MVS the assembler takes its macros from #cmd("SYS1.MACLIB") and the other
libraries named in #cmd("SYSLIB"). On the workstation a macro library is a
directory, and each macro is a file in it. as370 searches, in this order:

+ the directories given with #cmd("-I"), in the order given\;
+ the directories in the environment variable #cmd("AS370_MACLIB"),
  separated by colons\;#idx("AS370_MACLIB")
+ the macro library of the installed toolchain.

#idx("macro library", "of the toolchain")
The macro library of the toolchain holds three kinds of member:

- the macros that the code generated by cc370 uses: #cmd("PDPTOP"),
  #cmd("PDPPRLG") and #cmd("PDPEPIL")\;
- the macros of the C library\;
- the members of #cmd("SYS1.MACLIB") that the C library is built with, among
  them #cmd("SAVE"), #cmd("RETURN"), #cmd("WTO"), #cmd("GETMAIN"),
  #cmd("FREEMAIN"), #cmd("OPEN"), #cmd("CLOSE"), #cmd("DCB"),
  #cmd("ATTACH"), #cmd("LINK") and #cmd("ESTAE").

That is enough for GREET, which is why @ug-asm-greet-session needed no
#cmd("-I"). It is not the whole of #cmd("SYS1.MACLIB"), and a program that
uses another macro fails with an undefined operation code. The program CLOCK
in @ug-asm-clock-src uses #cmd("TIME"), which is not among them.

#fig(caption: [CLOCK, a program that uses the TIME macro])[
  #code(read("../ex/ug-asm/clock.asm"), numbers: true)
] <ug-asm-clock-src>

To provide the macro:

+ Copy the member #cmd("TIME") from #cmd("SYS1.MACLIB") on your system to a
  directory of your own, for example #cmd("maclib"). Transfer it as text,
  with translation from EBCDIC to ASCII: a macro is source, not a binary
  file. The transfer programs described in @ug-transfer work in this
  direction too.
+ Name the file after the member. as370 finds the member #cmd("TIME") as
  #cmd("TIME"), #cmd("time"), #cmd("TIME.mac") or #cmd("time.macro"), among
  other spellings.
+ Assemble with #cmd("-I maclib").

@ug-asm-clock-session shows the assembly before and after.

#fig(caption: [A missing macro, and the same assembly with a macro
  library])[
  #screen(raw(read("../ex/ug-asm/clock.txt")))
] <ug-asm-clock-session>

#note[A directory that does not exist is skipped without a message. A
misspelled #cmd("-I") shows itself only as an undefined operation code.]

To use your own copy of #cmd("SYS1.MACLIB") for every assembly, without
#cmd("-I"), set #cmd("AS370_MACLIB") to its directory in your shell profile.
The members of the toolchain's own library are still found, because that
library is searched last\; a member of the same name in your directory is
found first.

== How C Calls a Routine <ug-asm-linkage>

#idx("linkage convention")
#idx("calling convention")
C and assembler code can call each other because both follow one linkage
convention. It is the standard MVS convention, with one addition for the
stack of the C program. @ug-asm-regs-tab lists the registers involved.

#tab(caption: [Registers at a call])[
  #table(columns: (0.75in, 1fr),
    [Register], [Contents],
    [R1], [On entry, the address of the parameter list.],
    [R13], [On entry, the address of the caller's save area, which is part
      of the caller's stack frame. Its word at offset 76, the next
      available byte (NAB), addresses the free part of the C stack.],
    [R14], [On entry, the return address.],
    [R15], [On entry, the entry point address of the routine called. On
      return, the function value: an #cmd("int") or a pointer, or a
      #cmd("char") or #cmd("short") widened to a full word.],
    [R0], [On entry to a function that returns a structure, the address of
      the area for the result.],
    [FPR0], [On return, the value of a function that returns
      #cmd("float") or #cmd("double").],
  )
] <ug-asm-regs-tab>

#idx("parameter list")
The parameter list holds the _values_ of the arguments, one after the
other, not their addresses. An #cmd("int"), a pointer, a #cmd("char") and a
#cmd("short") take one full word each, a #cmd("double") a doubleword. The
last word is not marked: unlike the parameter list that #cmd("EXEC PGM=")
passes, it has no high-order bit set. A routine called from C must
therefore know how many arguments it receives.

A routine must return with R2 to R14 as they were when it was entered. The
usual way is #cmd("STM 14,12,12(13)") on entry, into the caller's save
area, and #cmd("L 14,12(,13)") and #cmd("LM 0,12,20(13)") on return, which
leave R15, the function value, alone.

@ug-asm-call-s shows the code that #cmd("cc370 -O1 -S") generates for a
call. The C source is

```
extern int addup(int n, const int *v);

int total3(const int *v)
{
    return addup(3, v);
}
```

#fig(caption: [The code cc370 generates for a call of #cmd("addup")])[
  #code(read("../ex/ug-asm/call.s").split("\n").slice(5, 23).join("\n"),
    numbers: true)
] <ug-asm-call-s>

The function #cmd("TOTAL3") keeps the address of its own parameter list in
R11 (line 9) and reads its argument as #cmd("0(11)"). For the call, it
builds the parameter list of #cmd("addup") in its own stack frame, at offset
88 from R13, with the value 3 and the pointer (lines 12 and 13), points R1
at it, and branches to #cmd("ADDUP") through a V-type address constant. The
result arrives in R15, where it is also the result of #cmd("TOTAL3").

== Calling Assembler from C <ug-asm-asmfromc>

#idx("assembler language", "called from C")
@ug-asm-addup shows ADDUP, the routine that SUMUP calls to add its
numbers. In C it is the function

```
int addup(int n, const int *v);
```

#fig(caption: [ADDUP, an assembler routine called from C])[
  #code(read("../ex/ug-asm/addup.asm"), numbers: true)
] <ug-asm-addup>

ADDUP saves the caller's registers in the caller's save area, loads its two
arguments from the parameter list, adds the words, and returns the sum in
R15. It calls nothing, so it needs no save area or stack frame of its own.

#idx("external names")
The C program declares the routine and calls it like any C function, as
@ug-asm-sumup-c shows. What connects the two is the external name. cc370
makes the external name of a C function by cutting its name to eight
characters, changing lower case to upper case and the underscore to
#cmd("@"): #cmd("addup") becomes #cmd("ADDUP"). Name the control section or
entry point of the assembler routine accordingly (see also
@ug-compile-names). When the C name cannot be
spelled that way, give it an #cmd("asm") label that names the external name
exactly:

```
extern int add_numbers(int n, const int *v) asm("ADDUP");
```

#fig(caption: [SUMUP, the main program in C])[
  #code(read("../ex/ug-asm/sumup.c"), numbers: true)
] <ug-asm-sumup-c>

Keep the declaration in one place, best in a header that the C sources
include. Nothing checks that the assembler routine expects the arguments
that the C declaration describes.

== Calling C from Assembler <ug-asm-cfromasm>

#idx("assembler language", "calling C")
#idx("PDPPRLG")#idx("PDPEPIL")
A C function expects a C stack: its prologue takes its stack frame from the
next available byte at offset 76 of the save area that R13 addresses. An
assembler routine that calls C must therefore pass, in R13, a save area that
is part of the C stack. The simplest way is to give the routine a stack
frame of its own, with the macros that cc370 uses for every C function:

#deflist(width: 1.45in,
  [#cmd("PDPPRLG")], [#var("name") #cmd("PDPPRLG") #cmd("FRAME=")#var("n")#cmd(",BASER=")#var("r")#cmd(",ENTRY=")#var("YES|NO")
    #linebreak()
    saves the caller's registers, loads the base register #var("r") with the
    entry point address and establishes it with #cmd("USING"), takes a frame
    of #var("n") bytes from the C stack and points R13 at it.
    #cmd("ENTRY=YES") also writes an #cmd("ENTRY") statement for
    #var("name")\; with #cmd("ENTRY=NO") and no #var("name"), the routine is
    entered at the beginning of its control section. The parameter
    #cmd("CINDEX="), which cc370 writes, has no effect.],
  [#cmd("PDPEPIL")], [releases the frame, restores the caller's registers
    except R15, and returns.],
)

The first 88 bytes of a frame hold the save area and words that the run
time uses. The parameter lists for the calls the routine makes start at
offset 88. Make #var("n") 88 plus the size of the largest parameter list,
rounded up to a multiple of 8.

@ug-asm-report shows REPORT, which SUMUP calls as

```
void report(int sum, int average);
```

and which calls #cmd("printf") to print its two arguments.

#fig(caption: [REPORT, an assembler routine that calls #cmd("printf")])[
  #code(read("../ex/ug-asm/report.asm"), numbers: true)
] <ug-asm-report>

#cmd("FRAME=104") leaves room for the three words of the parameter list of
#cmd("printf"): the address of the format, and the two numbers, which are
copied from REPORT's own parameter list. The format is an EBCDIC string as
C would have made it: the newline is #cmd("X'15'"), the newline of the C
library, and the string ends with #cmd("X'00'"). #cmd("printf") is called
through the V-type constant #cmd("=V(PRINTF)")\; #cmd("PRINTF") is the
external name of the C function.

@ug-asm-report-lst shows the listing of REPORT, with the statements that
#cmd("PDPPRLG") and #cmd("PDPEPIL") generate, marked #cmd("+").

#fig(caption: [Listing of REPORT (source statements)])[
  #set par(justify: false, leading: 0.32em)
  #text(font: mono-font, size: 6.1pt,
    read("../ex/ug-asm/report.lst").replace("\f", "").split("\n")
      .slice(5, 39).map(l => l.trim(at: end)).join("\n"))
] <ug-asm-report-lst>

#note[An assembler routine can call C only while a C program is running,
that is, in a program that was entered at #cmd("@@CRT0"), the C start-up,
and that called the routine from C. The start-up builds the C stack and the
run time that #cmd("printf") and the other library functions use. A program
written entirely in assembler, such as GREET, has neither, and cannot call
#cmd("printf") this way. Write the main program in C and call the assembler
code from it, as SUMUP does.]

== Building SUMUP <ug-asm-build>

#idx("cc370", "with assembler sources")
SUMUP is built from three sources:

+ Assemble #cmd("addup.asm") and #cmd("report.asm") with as370.
+ Compile #cmd("sumup.c") into an object module with #cmd("cc370 -c").
+ Link the three object modules with cc370, which links the C library, and
  with it the C start-up.

@ug-asm-sumup-session shows the commands. #cmd("-flinker-output=xmit")
writes #cmd("sumup.xmit") beside the load module, ready to be sent to MVS.

#fig(caption: [Building SUMUP])[
  #screen(raw(read("../ex/ug-asm/sumup.txt")))
] <ug-asm-sumup-session>

cc370 does not assemble a file named #cmd(".asm"): it passes every file it
does not recognize to ld370. Assemble such files with as370 first, as here,
or give cc370 #cmd("-x assembler") in front of them.

SUMUP builds and links without a message, but it is not yet correct.
@ug-diag shows how the error is found.
