#!/bin/sh
# Write the toolchain's version header: mkversion.sh OUT
#
# OUT gets the version from VERSION (the one source) and the commit the tree
# was built from.  It is rewritten ONLY when that content changes, so a build
# after a commit recompiles exactly the files that print the version, and an
# unchanged commit rebuilds nothing.  A -DCOMMIT on the command line cannot do
# that: make sees no changed prerequisite and keeps the object with the old
# hash (mvslovers/mbt#59).
#
# The commit is `unknown' outside a git checkout of THIS tree -- a release
# tarball, or a tree unpacked inside some other repository, whose HEAD says
# nothing about these sources.  A tree with uncommitted changes to tracked
# files gets `-dirty': it was not built from the commit alone.
set -e
out=$1
root=$(cd "$(dirname "$0")/.." && pwd -P)
ver=$(tr -d ' \t\r\n' < "$root/VERSION")
commit=unknown
top=$(git -C "$root" rev-parse --show-toplevel 2>/dev/null || true)
if [ -n "$top" ] && [ "$(cd "$top" && pwd -P)" = "$root" ]; then
    c=$(git -C "$root" rev-parse --short HEAD 2>/dev/null || true)
    if [ -n "$c" ]; then
        commit=$c
        git -C "$root" diff --quiet HEAD -- 2>/dev/null || commit="$c-dirty"
    fi
fi
tmp="$out.tmp.$$"
{
    echo "/* Generated by common/mkversion.sh -- do not edit, do not commit. */"
    echo "#define CC370_VERSION \"$ver\""
    echo "#define CC370_COMMIT  \"$commit\""
} > "$tmp"
if [ -f "$out" ] && cmp -s "$tmp" "$out"; then rm -f "$tmp"; else mv -f "$tmp" "$out"; fi
